[project]
name = "redshift-mcp"
version = "0.1.0"
description = "MCP server for Redshift based on username and password authentication"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.0",
    "redshift-connector>=2.1.8",
    "sqlglot[rs]>=27.0.0",
]
